[project]
name = "protoc-gen-sqlmodel"
version = "0.1.0"
description = "protoc plugin to generate SQLModel classes"
readme = "README.md"
license = { file = "LICENSE" }
authors = [{ name = "River Studio", email = "git@river-studio.net" }]
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3.14",
]
requires-python = ">=3.14"
dependencies = [
    "logging>=0.4.9.6",
    "protobuf-py>=0.4.0",
    "protoc-gen-py>=0.4.0",
    "sqlmodel>=0.0.42",
]

[project.scripts]
protoc-gen-sqlmodel = "protoc_gen_sqlmodel:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
