syntax = "proto3";

package parley.tables;

import "sqlmodel_extensions.proto";


message User {
  option (example.sqlmodel.table) = true;

  string id = 1 [
    (example.sqlmodel.default) = "None",
    (example.sqlmodel.pguuid7) = true

  ];
  // contact details, other socials, bio, etc.
  map<string, string> user_details = 3 [
    (example.sqlmodel.sa_type) = "sqlmodel.JSON"
  ];
  // message layer security deatils for e2ee
  map<string, string> mls_details = 4 [
    (example.sqlmodel.sa_type) = "sqlmodel.JSON"
  ];
  
  repeated Channel channels = 5 [
    (example.sqlmodel.relationship) = true,
    (example.sqlmodel.back_populates) = "users",
    (example.sqlmodel.link_model) = "UsersCommunesLink"
  ];
}

message Channel {
  option (example.sqlmodel.table) = true;

  string id = 1 [
    (example.sqlmodel.default) = "None",
    (example.sqlmodel.pguuid7) = true


  ];
  
  // commune is many to one relationship
  optional string commune_id = 3 [
    (example.sqlmodel.default) = "None",
    (example.sqlmodel.foreign_key) = "commune.id"
  ];
  optional Commune commune = 4 [
    (example.sqlmodel.relationship) = true,
    (example.sqlmodel.back_populates) = "channels"
  ];

  // category is many to one relationship
  optional string category_id = 5 [
    (example.sqlmodel.default) = "None",
    (example.sqlmodel.foreign_key) = "category.id"
  ];
  optional Category category = 6 [
    (example.sqlmodel.relationship) = true,
    (example.sqlmodel.back_populates) = "categories"
  ];

  // message layer security deatils for e2ee
  map<string, string> mls_details = 7 [
    (example.sqlmodel.sa_type) = "sqlmodel.JSON"
  ];

}

message UsersCommunesLink {
  option (example.sqlmodel.table) = true;

  string user_id = 1 [
    (example.sqlmodel.default) = "None",
    (example.sqlmodel.foreign_key) = "user.id",
    (example.sqlmodel.primary_key) = true
  ];
  string commune_id = 2 [
    (example.sqlmodel.default) = "None",
    (example.sqlmodel.foreign_key) = "commune.id",
    (example.sqlmodel.primary_key) = true
  ];
}

message Category {
  option (example.sqlmodel.table) = true;

  string id = 1 [
    (example.sqlmodel.default) = "None",
    (example.sqlmodel.pguuid7) = true
  ];
  
  map<string, string> category_details = 3 [
    (example.sqlmodel.sa_type) = "sqlmodel.JSON"
  ];

  repeated Channel channels = 4 [
    (example.sqlmodel.relationship) = true,
    (example.sqlmodel.back_populates) = "category"
  ];
  // commune is many to one relationship
  optional string commune_id = 5 [
    (example.sqlmodel.default) = "None",
    (example.sqlmodel.foreign_key) = "commune.id"
  ];
  optional Commune commune = 6 [
    (example.sqlmodel.relationship) = true,
    (example.sqlmodel.back_populates) = "categories"
  ];
}

message Commune {
  option (example.sqlmodel.table) = true;

  string id = 1 [
    (example.sqlmodel.default) = "None",
    (example.sqlmodel.pguuid7) = true

  ];
  
  map<string, string> commune_details = 3 [
    (example.sqlmodel.sa_type) = "sqlmodel.JSON"
  ];

  repeated Channel channels = 4 [
    (example.sqlmodel.relationship) = true,
    (example.sqlmodel.back_populates) = "commune"
  ];
  repeated Category categories = 5 [
    (example.sqlmodel.relationship) = true,
    (example.sqlmodel.back_populates) = "commune"
  ];
  // users is many to many relationship
  repeated User users = 6 [
    (example.sqlmodel.relationship) = true,
    (example.sqlmodel.back_populates) = "communes",
    (example.sqlmodel.link_model) = "UsersCommunesLink"
  ];
}
