# Generated from sqlmodel_extensions.proto. DO NOT EDIT.
# Generated by protoc-gen-py v0.4.0 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Final, TYPE_CHECKING

from protobuf import Extension
from protobuf._codegen import file_desc
from protobuf.wkt import FieldOptions, MessageOptions, descriptor_pb

if TYPE_CHECKING:
    from protobuf import DescFile


ext_table: Final[Extension[MessageOptions, bool]] = Extension()
"""
```proto
extend google.protobuf.MessageOptions { optional bool table = 50001 [json_name = "[example.sqlmodel.table]"] }
```
"""

ext_sqlmodel_type: Final[Extension[FieldOptions, str]] = Extension()
"""
```proto
extend google.protobuf.FieldOptions { optional string sqlmodel_type = 50002 [json_name = "[example.sqlmodel.sqlmodel_type]"] }
```
"""


_DESC = file_desc(
    b'\n\x19sqlmodel_extensions.proto\x12\x10example.sqlmodel\x1a google/protobuf/descriptor.proto:7\n\x05table\x18\xd1\x86\x03 \x01(\x08\x12\x1f.google.protobuf.MessageOptionsR\x05table:D\n\rsqlmodel_type\x18\xd2\x86\x03 \x01(\t\x12\x1d.google.protobuf.FieldOptionsR\x0csqlmodelTypeb\x06proto3',
    [
        descriptor_pb.desc(),
    ],
    {
        "table": ext_table,
        "sqlmodel_type": ext_sqlmodel_type,
    },
)


def desc() -> DescFile:
    """Returns the descriptor for the file `sqlmodel_extensions.proto`."""
    return _DESC
