syntax = "proto3";

package example.sqlmodel;

import "google/protobuf/descriptor.proto";

// Marks a protobuf message as a SQLModel table.
extend google.protobuf.MessageOptions {
  bool table = 50001;
}

// Overrides the default protobuf-to-SQLModel field conversion.
extend google.protobuf.FieldOptions {
  string sa_type = 50002;
  bool primary_key = 50003;
  string sqlmodel_default = 50004;
  string sqlmodel_default_factory = 50005;
  string py_default = 50006;
  bool index = 50007;
  string foreign_key = 50008;
  bool relationship = 50009;
  string back_populates = 50010;
  bool cascade_delete = 50011;
  string on_delete = 50012;
  string passive_deletes = 50013;
  string link_model = 50014;
  string server_default = 50015;
  string pg_uuid7 = 50016;  // special plugin feature to set up a uuid7 column
}
